<?php

declare(strict_types=1);

if (!defined('_PS_VERSION_')) {
    exit;
}

// Defensive: register the module's autoloader ourselves rather than assume
// gmcfeedmanager.php already ran in this request (require_once is a no-op
// if it did).
require_once __DIR__ . '/../../src/autoload.php';

use GmcFeedManager\Service\ProductDataTransformer;

/**
 * Public XML feed endpoint: /module/gmcfeedmanager/feed?token=...&id_lang=1&id_currency=1
 *
 * Streams a Google RSS 2.0 (g: namespace) feed directly to php://output via
 * XMLWriter, fetching the catalog in small SQL chunks (LIMIT/OFFSET) so
 * memory use stays flat no matter how large the catalog is. No Smarty, no
 * theme, no session -- this controller writes raw bytes and exits.
 */
class GmcfeedmanagerFeedModuleFrontController extends ModuleFrontController
{
    public $auth = false;
    public $ssl = false;

    private const DEFAULT_CHUNK_SIZE = 250;

    public function initHeader(): void
    {
        // Intentionally empty: skip theme/CSS/JS/hook bootstrapping entirely.
    }

    public function initFooter(): void
    {
        // Intentionally empty, see initHeader().
    }

    public function setMedia($isAjax = false): void
    {
        // Intentionally empty: no front-office assets are needed for a feed.
    }

    public function initContent(): void
    {
        if (!$this->isTokenValid()) {
            $this->abort(403, 'Forbidden');
        }

        $idLang = $this->resolveLang();
        $idCurrency = $this->resolveCurrency();
        $idShop = (int) Tools::getValue('id_shop', (int) $this->context->shop->id);

        if ($idLang <= 0 || $idCurrency <= 0) {
            $this->abort(400, 'Invalid id_lang or id_currency');
        }

        $this->streamFeed($idLang, $idCurrency, $idShop);
        exit;
    }

    private function isTokenValid(): bool
    {
        $expected = (string) Configuration::get(Gmcfeedmanager::CONFIG_FEED_TOKEN);
        $provided = (string) Tools::getValue('token', '');

        return $expected !== '' && $provided !== '' && hash_equals($expected, $provided);
    }

    private function resolveLang(): int
    {
        $idLang = (int) Tools::getValue('id_lang', (int) Configuration::get(Gmcfeedmanager::CONFIG_ID_LANG));

        return Validate::isLoadedObject(new Language($idLang)) ? $idLang : 0;
    }

    private function resolveCurrency(): int
    {
        $idCurrency = (int) Tools::getValue('id_currency', (int) Configuration::get(Gmcfeedmanager::CONFIG_ID_CURRENCY));

        return Validate::isLoadedObject(new Currency($idCurrency)) ? $idCurrency : 0;
    }

    private function abort(int $httpCode, string $message): void
    {
        while (ob_get_level() > 0) {
            ob_end_clean();
        }

        http_response_code($httpCode);
        header('Content-Type: text/plain; charset=utf-8');
        echo $message;
        exit;
    }

    private function streamFeed(int $idLang, int $idCurrency, int $idShop): void
    {
        while (ob_get_level() > 0) {
            ob_end_clean();
        }

        set_time_limit(0);
        header('Content-Type: application/xml; charset=utf-8');

        $chunkSize = (int) Configuration::get(Gmcfeedmanager::CONFIG_CHUNK_SIZE) ?: self::DEFAULT_CHUNK_SIZE;

        $writer = new XMLWriter();
        $writer->openURI('php://output');
        $writer->setIndent(true);
        $writer->startDocument('1.0', 'UTF-8');

        $writer->startElement('rss');
        $writer->writeAttribute('version', '2.0');
        $writer->writeAttribute('xmlns:g', 'http://base.google.com/ns/1.0');

        $writer->startElement('channel');
        $writer->writeElement('title', Configuration::get('PS_SHOP_NAME') . ' - Google Merchant Feed');
        $writer->writeElement('link', $this->context->link->getPageLink('index', null, $idLang));
        $writer->writeElement('description', 'Google Merchant Center product feed generated by gmcfeedmanager.');

        $transformer = new ProductDataTransformer();
        $offset = 0;

        do {
            $rows = Db::getInstance()->executeS(
                $this->buildChunkQuery($idShop, $chunkSize, $offset)
            );

            if (!$rows) {
                break;
            }

            foreach ($rows as $row) {
                $this->writeRow($writer, $transformer, $row, $idLang, $idCurrency, $idShop);
            }

            $rowCount = count($rows);
            $offset += $chunkSize;

            // Push what we have to the client and free XMLWriter's internal
            // buffer before pulling the next chunk from MySQL.
            $writer->flush();
            if (function_exists('fastcgi_finish_request') === false) {
                @flush();
            }

            unset($rows);
        } while ($rowCount === $chunkSize);

        $writer->endElement(); // channel
        $writer->endElement(); // rss
        $writer->endDocument();
        $writer->flush();
    }

    /**
     * @param array<string, mixed> $row
     */
    private function writeRow(
        XMLWriter $writer,
        ProductDataTransformer $transformer,
        array $row,
        int $idLang,
        int $idCurrency,
        int $idShop
    ): void {
        $idProduct = (int) $row['id_product'];
        $idProductAttribute = (int) $row['id_product_attribute'];

        $product = new Product($idProduct, false, $idLang, $idShop);
        if (!Validate::isLoadedObject($product) || !$product->active) {
            return;
        }

        $combination = null;
        if ($idProductAttribute > 0) {
            $combination = new Combination($idProductAttribute);
            if (!Validate::isLoadedObject($combination)) {
                $combination = null;
            }
        }

        $data = $transformer->transform($product, $idLang, $idCurrency, $combination, $idShop);

        unset($product, $combination);

        if (!empty($data['excluded'])) {
            return;
        }

        $this->writeItem($writer, $data);
    }

    /**
     * @param array<string, mixed> $data
     */
    private function writeItem(XMLWriter $writer, array $data): void
    {
        $writer->startElement('item');

        $writer->writeElement('g:id', (string) $data['id']);
        $writer->writeElement('title', (string) ($data['title'] ?? ''));
        $writer->writeElement('description', (string) ($data['description'] ?? ''));
        $writer->writeElement('link', (string) ($data['link'] ?? ''));
        $writer->writeElement('g:image_link', (string) ($data['image_link'] ?? ''));

        foreach ((array) ($data['additional_image_link'] ?? []) as $imageUrl) {
            $writer->writeElement('g:additional_image_link', (string) $imageUrl);
        }

        $writer->writeElement('g:availability', (string) ($data['availability'] ?? 'in stock'));
        $writer->writeElement('g:condition', (string) ($data['condition'] ?? 'new'));
        $writer->writeElement('g:price', (string) ($data['price'] ?? ''));

        if (!empty($data['sale_price'])) {
            $writer->writeElement('g:sale_price', (string) $data['sale_price']);
        }

        if (!empty($data['sale_price_effective_date'])) {
            $writer->writeElement('g:sale_price_effective_date', (string) $data['sale_price_effective_date']);
        }

        if (!empty($data['item_group_id'])) {
            $writer->writeElement('g:item_group_id', (string) $data['item_group_id']);
        }

        if (!empty($data['gtin'])) {
            $writer->writeElement('g:gtin', (string) $data['gtin']);
        }

        if (!empty($data['mpn'])) {
            $writer->writeElement('g:mpn', (string) $data['mpn']);
        }

        if (!empty($data['identifier_exists'])) {
            $writer->writeElement('g:identifier_exists', (string) $data['identifier_exists']);
        }

        if (!empty($data['brand'])) {
            $writer->writeElement('g:brand', (string) $data['brand']);
        }

        if (!empty($data['google_product_category'])) {
            $writer->writeElement('g:google_product_category', (string) $data['google_product_category']);
        }

        if (!empty($data['product_type'])) {
            $writer->writeElement('g:product_type', (string) $data['product_type']);
        }

        foreach (['color', 'size', 'gender', 'age_group'] as $apparelField) {
            if (!empty($data[$apparelField])) {
                $writer->writeElement('g:' . $apparelField, (string) $data[$apparelField]);
            }
        }

        for ($i = 0; $i < 5; ++$i) {
            $key = 'custom_label_' . $i;
            if (!empty($data[$key])) {
                $writer->writeElement('g:' . $key, (string) $data[$key]);
            }
        }

        $writer->endElement(); // item
    }

    /**
     * One row per sellable unit: simple products get id_product_attribute=0,
     * products with combinations get one row per combination. A stable
     * ORDER BY keeps LIMIT/OFFSET pagination consistent across chunks.
     */
    private function buildChunkQuery(int $idShop, int $limit, int $offset): string
    {
        return '
            SELECT p.`id_product`, IFNULL(pa.`id_product_attribute`, 0) AS id_product_attribute
            FROM `' . _DB_PREFIX_ . 'product` p
            INNER JOIN `' . _DB_PREFIX_ . 'product_shop` ps
                ON ps.`id_product` = p.`id_product` AND ps.`id_shop` = ' . (int) $idShop . '
            LEFT JOIN `' . _DB_PREFIX_ . 'product_attribute` pa
                ON pa.`id_product` = p.`id_product`
            WHERE p.`active` = 1
              AND ps.`active` = 1
              AND ps.`visibility` != "none"
            ORDER BY p.`id_product` ASC, pa.`id_product_attribute` ASC
            LIMIT ' . (int) $limit . ' OFFSET ' . (int) $offset;
    }
}
